---
title: "Untitled"
output: html_document
---
```{r}
library(plyr)
library(ggplot2)
library(dplyr)
library(tidyr)
datacombine<-function(chr1,chr2,chr3,chr4){
  data1 <-read.csv(chr1,skip=3,colClasses = c("character",rep("NULL",2),rep("integer",5),rep("NULL",3)))
  data2 <-read.csv(chr2,skip=3,colClasses = c("character",rep("NULL",2),rep("integer",5),rep("NULL",3)))
  data3 <-read.csv(chr3,skip=3,colClasses = c("character",rep("NULL",2),rep("integer",5),rep("NULL",3)))
  data4 <-read.csv(chr4,skip=3,colClasses = c("character",rep("NULL",2),rep("integer",5),rep("NULL",3)))
  return(rbind(data1,data2,data3,data4))
}
bjdirty<-datacombine("bj2012.csv","bj2013.csv","bj2014.csv","bj2015.csv")
str(bjdirty)
```

* 2. Create a new factor variable "week" to the  dataset, set 1 as the weekday , 0 as the weekend.

```{r}
#1/1/2012 is Sunday, set variable week as 0
n<-dim(bjdirty)[1]/24 #Total days
l<-n%/%7 # Total weeks (from Mon to Sun, 7 days)
m<-n%%7-1 # here m = 4, means for 12/28/2015 to 12/31/2015 , week = 1
week<-c(rep(0,24),rep(rep(c(rep(1,5),rep(0,2)),each=24),l),rep(c(1,1,1,1),each=24))
# week variable from 1/1/2012 to 12/31/2015
bjdirty$week<-week
str(bjdirty)
```
* 3. Find all holidays (or some long-term holidays ,like spring festival) for each year, changing the corresponding week vaules.
```{r}
#Holiday informations from the Chinese Goverment website :
#2012 :http://www.gov.cn/zwgk/2011-12/06/content_2012097.htm
#2013 :http://www.gov.cn/zwgk/2012-12/10/content_2286598.htm
#2014 :http://www.gov.cn/zwgk/2013-12/11/content_2546204.htm
#2015 :http://www.gov.cn/zhengce/content/2014-12/16/content_9302.htm

#for 2012
M2012.h<-c(rep(1,10),rep(4,5),5,rep(6,3),9,rep(10,7))
D2012.h<-c(1:3,22:28,2:4,29:30,1,22:24,30,1:7)
WE2012<-paste(2012,M2012.h,D2012.h,sep="/")
M2012.w<-c(1,1,3,4,4,9)
D2012.w<-c(21,29,31,1,28,29)
WD2012<-paste(2012,M2012.w,D2012.w,sep="/")

#for 2013
M2013.h<-c(rep(1,3),rep(2,7),rep(4,5),5,rep(6,3),rep(9,3),rep(10,7))
D2013.h<-c(1:3,9:15,4:6,29:30,1,10:12,19:21,1:7)
WE2013<-paste(2013,M2013.h,D2013.h,sep="/")
M2013.w<-c(1,1,2,2,4,4,4,6,6,9,9,10)
D2013.w<-c(5,6,16,17,7,27,28,8,9,22,29,12)
WD2013<-paste(2013,M2013.w,D2013.w,sep="/")

#for 2014
M2014.h<-c(rep(1,2),rep(2,6),4,rep(5,3),6,9,rep(10,7))
D2014.h<-c(1,31,1:6,5,1:3,2,8,1:7)
WE2014<-paste(2014,M2014.h,D2014.h,sep="/")
M2014.w<-c(1,2,4,5,9,10)
D2014.w<-c(26,8,7,4,28,11)
WD2014<-paste(2014,M2014.w,D2014.w,sep="/")

#for 2015
M2015.h<-c(rep(1,3),rep(2,7),4,5,6,9,rep(10,7))
D2015.h<-c(1:3,18:24,5,20,27,1:7)
WE2015<-paste(2015,M2015.h,D2015.h,sep="/")
M2015.w<-c(1,2,2,4,6,10)
D2015.w<-c(4,15,28,6,22,10)
WD2015<-paste(2015,M2015.w,D2015.w,sep="/")

WE<-c(WE2012,WE2013,WE2014,WE2015)
WD<-c(WD2012,WD2013,WD2014,WD2015)

bjdirty<-bjdirty%>% 
mutate(date = paste(Year,Month,Day,sep="/"))
bjdirty0<-bjdirty%>%
filter(date %in% WE)%>%
mutate(week = 0)
bjdirty1<-bjdirty%>%
filter(date %in% WD)%>%
mutate(week = 1)
bjdirty2<-bjdirty%>%
filter(!date %in% c(WD,WE))

bjweek<-rbind(bjdirty0,bjdirty1,bjdirty2) %>%
arrange(Year,Month,Day)

```

* 4. Dataclean, add the pollution level accroding to the mean daily value.

```{r}
dataclean<-function(data){
    newdata<-data %>%
    filter(Value > 0) %>%
    group_by(Month,Day) %>%
    mutate(mean_Value_Day = mean(Value)) %>%
    ungroup()
    return(newdata)
}
bjclean<-dataclean(bjweek)
bjclean$DailyIndex<-as.numeric(bjclean$mean_Value_Day>=100)
bjclean$week<-gsub("0",replacement="weekend",bjclean$week)
bjclean$week<-gsub("1",replacement="weekday",bjclean$week)
bjclean$DailyIndex<-gsub("0",replacement="Light",bjclean$DailyIndex)
bjclean$DailyIndex<-gsub("1",replacement="Heavy",bjclean$DailyIndex)
knitr::kable(head(bjclean))
```

```{r}
BJ<-summarise(group_by(bjclean,Year,Month,Day),mid=median(Value))
k=c()
for(i in 1:(dim(BJ)[1]-3)){
  k[i]=mean(BJ$mid[(i+2):(i+3)])-mean(BJ$mid[i:(i+1)])
}
n=order(k)[1:10]
l=c(n,n+1,n+2,n+3)
l=unique(l)
BJ[sort(l),]
result1=BJ[sort(l),c(1,2,4)]
ggplot(data=result1,aes(x=Month,y=mid))+geom_point(aes(color = Year))


BJM<-summarise(group_by(BJ,Year,Month),mean=mean(mid))
d=BJM$mean
t=ts(d,frequency = 12,start=c(2012,1))
g<- decompose(t)
plot(g)

t=ts(k,frequency = 365,start=c(2012,1,1))
g<- decompose(t)
x=order(g$random)[1:10]
y=c(x,x+1,x+2,x+3)
y=unique(y)
ggplot(BJ[sort(y),],aes(x=Month,y=mid))+geom_point(aes(color = Year))
BJ[sort(y),c(1,2,3)]

ggplot(BJ[1320:1340,],aes(x=Day,y=mid))+geom_point(aes(color = Month))

ggplot(BJ[1355:1375,],aes(x=Day,y=mid))+geom_point(aes(color = Month))

```